### ISSUE TITLE
Module not callable error

### ISSUE THREAD

**Issue by avirklol** [avirklol/projects_pub#1]
Hey @ericbdev, could you have a look at text_adventure/llm_playground/llm_app.py and let me know where my fuck up is?

**Comment by avirklol** [comment]
Here's the error:

```
2024-02-07 20:23:20.851 Uncaught app exception
Traceback (most recent call last):
  File "/Users/annandvirk/.pyenv/versions/the_bastion/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
  File "/Users/annandvirk/code/avirklol/projects_pub/text_adventure/llm_playground/llm_app.py", line 19, in <module>
    generate_response(input)
  File "/Users/annandvirk/code/avirklol/projects_pub/text_adventure/llm_playground/llm_app.py", line 10, in generate_response
    llm = openai(temperature=0.7, openai_api_key=openai_api_key)
TypeError: 'module' object is not callable
```

**Comment by avirklol** [comment]
I pretty much followed the guide you showed me with some tweaks, based on other errors that were being thrown.

Example:

```
/Users/annandvirk/.pyenv/versions/the_bastion/lib/python3.10/site-packages/langchain/llms/__init__.py:548: LangChainDeprecationWarning: Importing LLMs from langchain is deprecated. Importing from langchain will no longer be supported as of langchain==0.2.0. Please import from langchain-community instead:

`from langchain_community.llms import openai`.

To install langchain-community run `pip install -U langchain-community`.
```

**Comment by ericbdev** [comment]
From the deprecation notice, I feel your gut was correct in your change. I looked at the docs, and maybe it's just a casing mismatch? 
https://api.python.langchain.com/en/latest/llms/langchain_openai.llms.base.OpenAI.html#

I'll pull the code tomorrow AM and try it out myself.

**Comment by ericbdev** [comment]
Out dated tutorials and docs are a pain in the butt :/ sorry for the mislead

https://github.com/avirklol/projects_pub/pull/2
I had to do some env changes to get pip happy installing, let me know your toughts on co-locating dependencies for projects

**Comment by avirklol** [comment]
No stress about the mislead. It's wild how many tutorials that exist that are completely outdated. 

I would have looked into it a bit more but had to hop off. Thanks for looking into it, Eric.

**Comment by ericbdev** [comment]
My pleasure, it was simple enough, and a good way to start the day off.
